# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

proc fib_sum(n: int): int = 
  var a = 1
  var b = 2
  for i in 1..n:
    echo a, " | ", b
    if a > n: return result
    if a %% 2 == 0: result += a
    a += b
    a  = a xor b
    b  = b xor a
    a  = a xor b

if isMainModule:
  echo fib_sum(4_000_000)
